### ISSUE TITLE
Action not executed

### ISSUE THREAD

**Issue by MasterPIC** [benlye/OctoPrint-ActionCommandsPlugin#3]
Hi,

I own an Anet A8, Marlin bugfix-2.0.x up to date.
I defined ACTION_ON_KILL to make the printer requesting an action on kill.
But when a thermal failure occurs the expected action is not detected by the plugin.

**In a few words I'm tempted to think that the action is not executed if an error is reported by the printer soon after the action request...**

I solved the issue by editing the firmware to make the printer requesting the action before going to report the error. So I edited my printer firmware by adding

`SERIAL_ECHOLNPGM("//action:" ACTION_ON_KILL);`

```
void Temperature::_temp_error(const int8_t heater, PGM_P const serial_msg, PGM_P const lcd_msg) {
  static bool killed = false;
  if (IsRunning()) {
    SERIAL_ECHOLNPGM("//action:" ACTION_ON_KILL);
    SERIAL_ERROR_START();
    serialprintPGM(serial_msg);
    SERIAL_ECHOPGM(MSG_STOPPED_HEATER);
    if (heater >= 0) SERIAL_ECHOLN((int)heater); else SERIAL_ECHOLNPGM(MSG_HEATER_BED);
  }
  #if DISABLED(BOGUS_TEMPERATURE_FAILSAFE_OVERRIDE)
    if (!killed) {
      Running = false;
      killed = true;
      kill(lcd_msg);
    }
    else
      disable_all_heaters(); // paranoia
  #endif
}
```
The plugin seems to be bugged since the action request can occur also after the error has been reported (before the printer has been killed obviously)...

Thanks
Armando

**Comment by benlye** [comment]
Stale issue, which seems more like a Marlin bug than a plugin problem - the plugin executes the code as soon as it receives the command.
