### ISSUE TITLE
Add Python 3 compatibility

### ISSUE THREAD

**Issue by Poikilos** [benlye/OctoPrint-ActionCommandsPlugin#4]
OctoPrint now supports Python 3 compatibility. Recently they added a plugin called "Python 3 Check" which suggests to the user to add an issue at the plugin's repo for adding Python 3 compatibilty.

**Comment by benlye** [comment]
This plugin already supports Python 3.

**Comment by benlye** [comment]
Wrong plugin.  This plugin does not yet support Python 3, but will soon ;-)

**Comment by benlye** [comment]
Done.  It will be available to install as soon as the plugin repo is updated.
https://github.com/OctoPrint/plugins.octoprint.org/pull/426
