### ISSUE TITLE
Add action startup

### ISSUE THREAD

**Issue by RChadwick7** [benlye/OctoPrint-ActionCommandsPlugin#6]
I'm looking to set GPIO pins for input and putput at startup, but I don't want to mess with system files so a backup will restore it. It looks like the Action Commands Plugin will do it, but is there an action that will run a system command on startup?

**Comment by benlye** [comment]
That's not really what this plugin does.  

Action commands are commands that are run in response to the printer sending a specifically formatted string to the OctoPrint host via the serial connection.  They're not just arbitrary commands that you can have your system run any time.
