### ISSUE TITLE
Run Commands with klipper

### ISSUE THREAD

**Issue by DasLukas** [benlye/OctoPrint-ActionCommandsPlugin#7]
I try to run commands created with this plugin while using klipper as firmware. I created a command named shutdown; system; sudo shutdown -h now. When i push it to the terminal like this `shutdown` i get following response:

```
Send: shutdown
Recv: // Unknown command:"SHUTDOWN"
Recv: ok
```

If I run `M118 shutdown` I get the following:

```
Send: M118 shutdown
Recv: echo: shutdown
Recv: ok
```

No action triggered.

I'm also configured klipper like written [here](https://github.com/KevinOConnor/klipper/blob/master/docs/Config_Reference.md#respond).

Is this a problem on the side of this plugin or by klipper?

**Comment by benlye** [comment]
I'm not familiar with Klipper at all, but looking at the documentation, I believe the command you need to use is this:

`RESPOND TYPE=command MSG=action:shutdown`

**Comment by DasLukas** [comment]
> `RESPOND TYPE=command MSG=action:shutdown`

I pushed this to the terminal but it seems the ActionCommandsPlugin not react to the command.

I also tried different syntaxes. 

```
Send: RESPOND TYPE=command MSG=action:shutdown
Recv: // action:shutdown
Send: RESPOND TYPE=command MSG=shutdown
Recv: // shutdown
Send: RESPOND TYPE=echo MSG=action:shutdown
Recv: echo: action:shutdown
Send: RESPOND TYPE=echo MSG=shutdown
Recv: echo: shutdown
```

**Comment by benlye** [comment]
Can you reconfigure the firmware to remove the space after `//`?

It seems like that might be stopping OctoPrint recognising the action command and sending it through to the plugin.

**Comment by DasLukas** [comment]
Found the problem! 

`RESPOND TYPE=command MSG=action:shutdown` is complete right. But case sensitive. I name it SHUTDOWN.

Thanks for your help.
