### ISSUE TITLE
Support for "echo" command ?

### ISSUE THREAD

**Issue by AntoineTurmel** [benlye/OctoPrint-ActionCommandsPlugin#8]
It would be nice to also have support for echo command:
M118 E1 mycommand

**Comment by benlye** [comment]
That's not the way action commands work; the hook only fires for lines in a specific format.  You can still use `M118`, but you have to use this syntax:

`M118 A1 action:mycommand`

My printer responds to action:poweroff, so sending `M118 A1 action:poweroff` triggers the action I have defined:

```
Send: M118 A1 action:poweroff
Recv: // action:poweroff
```

OctoPrint action hook documentation:
https://docs.octoprint.org/en/master/features/action_commands.html
https://docs.octoprint.org/en/master/plugins/hooks.html#octoprint-comm-protocol-action

**Comment by AntoineTurmel** [comment]
Ok thanks, I figured I would modify your plugin to use "octoprint.comm.protocol.gcode.received" hook instead to read from "echo" commands. It's working for me, is it ok if I fork your plugin and then publish a "EchoCommandsPlugin" ? I'll credit you as the main author of course.

The reason is M118 A1 action doesn't work on my printer stock firmware (Ender 3 v2), but M118 E1 is working.

**Comment by benlye** [comment]
'A1' and 'E1' are optional as far as I know.  Why not just use `M118 // action:mycommand`

**Comment by AntoineTurmel** [comment]
@benlye it just doesn't work with my stock firmware...

**Comment by benlye** [comment]
It seems like the right thing to do is fix/update your firmware, but if you want to create a new plugin feel free to do it that way.
